export const CREATE_MEMBER = "CREATE_MEMBER";
export const EDIT_MEMBER = "EDIT_MEMBER";
export const GET_MEMBERS = "GET_MEMBERS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const ASSIGN_MEMBER = "ASSIGN_MEMBER";
export const SHOW_DETAIL = "SHOW_DETAIL";